# Stage 1: Build Stage
FROM node:latest as build

ARG ENVIRONMENT=production

WORKDIR /usr/local/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
