services:
  backend:
    build:
      context: ./Backend/
    ports:
      - "5000:5000"
    depends_on:
      - database-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres_test
      FLASK_CONFIG: testing
     
  database-test:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres_test
    ports:
      - "5433:5432"

