services:
  frontend:
    build:
      context: ./Frontend/
      args:
        - ANGULAR_ENVIRONMENT=${ANGULAR_ENVIRONMENT:-production}
    ports:
      - "80:80"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.${ANGULAR_ENVIRONMENT}
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      USER_LAST_NAME: ${USER_LAST_NAME}
      USER_FIRST_NAME: ${USER_FIRST_NAME}

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    # Comment the following lines to prevent the database from being accessible from the outside
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data

volumes:
  postgresData:
    name: "postgresDataVolume"
