version: '3'

services:
  frontend:
    build:
      context: ../../Web-App/Frontend/
      args:
        - ANGULAR_ENVIRONMENT=${ANGULAR_ENVIRONMENT:-production}
    ports:
      - "80:80"

  backend:
    build:
      context: ../../Web-App/Backend/
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
    - POSTGRES_PW=${POSTGRES_PW}

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: postgres
    # Uncomment the following lines to prevent the database from being accessible from the outside
    ports:
      - "5432:5432"
