version: '3'

services:
  backend:
    build:
      context: ../../Web-App/Backend/
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    # Nächste Zeilen auskommentieren, um die Datenbank von außen nicht erreichbar zu machen
    ports:
     - "5432:5432"