FROM python:3.8

WORKDIR /app

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

RUN pip install gunicorn

EXPOSE 5000

CMD exec gunicorn --bind 0.0.0.0:5000 app:app
